export const API_AUTH = "http://127.0.0.1:8001";
export const API_FRIDGE = "http://127.0.0.1:8002";
export const API_RECIPE = "http://127.0.0.1:8003";

export const INGREDIENT_SUGGESTIONS = [
  "kurczak",
  "ryż",
  "makaron",
  "mleko",
  "jajko",
  "ser",
  "cebula",
  "czosnek",
  "pomidor",
  "ziemniaki",
  "marchew",
  "papryka",
  "wołowina",
  "wieprzowina",
  "tuńczyk",
  "łosoś",
  "masło",
  "olej",
  "oliwa",
  "śmietana",
  "jogurt",
  "chleb",
  "bułka",
  "mąka",
  "cukier",
  "sól",
  "pieprz",
  "bazylia",
  "oregano",
  "cukinia",
  "bakłażan",
  "fasola",
  "soczewica",
  "kukurydza",
  "groszek",
  "brokuł",
  "kalafior",
  "szpinak",
  "rukola",
  "sałata",
  "ogórek",
  "ketchup",
  "musztarda",
  "majonez",
  "jabłko",
  "banan",
  "truskawka",
  "czekolada",
  "ser mozzarella"
];

export const RECIPE_CATEGORIES = [
  "Śniadanie",
  "Obiad",
  "Kolacja",
  "Zupa",
  "Sałatka",
  "Deser",
  "Przekąska",
  "Szybkie",
  "Fit",
  "Mięsne",
  "Wegetariańskie",
  "Wegańskie"
];